## Humor dataset from previous version used in deep-sheep paper

In [1]:
import pandas as pd

In [14]:
annotations = pd.read_csv('data/HUMOR-DEEPSHEEP/annotations.csv')

df_text = pd.read_csv('data/HUMOR-DEEPSHEEP/annotations_by_tweet.csv')

In [6]:
annotations['vote'].unique()

array(['n', '3', '1', '4', '5', '2', 'x', 'd'], dtype=object)

In [7]:
annotations.count()

tweet_id      40430
session_id    40430
vote          40430
dtype: int64

In [ ]:
# n - not humorous
# x - skip?
# d - panowie z papera niestety nie podzielili sie informacjami o znaczeniu takowego symbolu

In [12]:
annotations[annotations['vote']=='x'].count()

tweet_id      17588
session_id    17588
vote          17588
dtype: int64

In [13]:
annotations

                 tweet_id                  session_id vote
0             21687865379  04hfu1edim4o69ihnmeas70jj3    n
1             21687865379  0re71cb38k4vbm0ab8ptfch9e1    3
2             21687865379  1edr5icem4mtn3dgfqv1o99he2    1
3             21687865379  eoqefm1vce3tecodb9i9g2avp7    4
4             21687865379  fic8u9o83q8vq2jt2t4ed9vra4    1
...                   ...                         ...  ...
40425  498640875581632512  0re71cb38k4vbm0ab8ptfch9e1    x
40426  498640875581632512  ftu0ov2469ncl5th6iqritm6o0    n
40427  498640875581632512  h1f2gvtplolcmuoi9didbl7285    x
40428  498642160540200960  fm7id2qd2mu7dd5lu6h1ses4b2    x
40429  498642160540200960  i2nhjkbhkbkir86llscpbg2no4    x

[40430 rows x 3 columns]

In [15]:
df_text

,id,text,account_id,x,1,2,3,4,5
0,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,174450359,0,7,0,2,1,0
1,21687932514,¿Qué es una elección? Lo que le pasa a un chin...,174450359,1,1,2,0,3,1
2,27561052090,"Si tu apellido fuera Melculo, ¿cómo te gustarí...",174450359,0,1,0,3,2,1
3,2057672085995520,Las piernas son las mejores amigas de una chic...,174450359,0,1,1,1,1,1
4,2100110548795392,¿Cuál es la diferencia entre un burro y una TV...,174450359,1,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...
15129,497835428242665472,Windows 9 también eliminaría la barra de opcio...,177694647,1,0,0,0,0,0
15130,497874858735587328,"Bañarse sin música, es como no bañarse.",1518218509,1,0,0,0,0,0
15131,498640871722856448,RT @MichelPesquera: Mi consejo del día... ¡Bue...,1518218509,1,0,0,0,0,0
15132,498640875581632512,RT @MichelPesquera: Las palabras que usamos pa...,1518218509,2,0,0,0,0,0
15133,498642160540200960,"RT @iMoviePhrases: Si eres bueno en algo, nunc...",1518218509,2,0,0,0,0,0

In [16]:
df_text['Sum'] = df_text[['x', '1', '2', '3', '4', '5']].sum(axis=1)

### more than 2 annotators annotated a tweet

In [24]:
df_text = df_text[df_text['Sum']>=2]

In [25]:
df_text.count()

id            8284
text          8284
account_id    8284
x             8284
1             8284
2             8284
3             8284
4             8284
5             8284
Sum           8284
dtype: int64

In [26]:
# Połączenie DataFrame'ów
merged_df = pd.merge(annotations, df_text, left_on='tweet_id', right_on='id', how='inner')

In [27]:
merged_df

,tweet_id,session_id,vote,id,text,account_id,x,1,2,3,4,5,Sum
0,21687865379,04hfu1edim4o69ihnmeas70jj3,n,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,174450359,0,7,0,2,1,0,10
1,21687865379,0re71cb38k4vbm0ab8ptfch9e1,3,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,174450359,0,7,0,2,1,0,10
2,21687865379,1edr5icem4mtn3dgfqv1o99he2,1,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,174450359,0,7,0,2,1,0,10
3,21687865379,eoqefm1vce3tecodb9i9g2avp7,4,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,174450359,0,7,0,2,1,0,10
4,21687865379,fic8u9o83q8vq2jt2t4ed9vra4,1,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,174450359,0,7,0,2,1,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31344,498640875581632512,0re71cb38k4vbm0ab8ptfch9e1,x,498640875581632512,RT @MichelPesquera: Las palabras que usamos pa...,1518218509,2,0,0,0,0,0,2
31345,498640875581632512,ftu0ov2469ncl5th6iqritm6o0,n,498640875581632512,RT @MichelPesquera: Las palabras que usamos pa...,1518218509,2,0,0,0,0,0,2
31346,498640875581632512,h1f2gvtplolcmuoi9didbl7285,x,498640875581632512,RT @MichelPesquera: Las palabras que usamos pa...,1518218509,2,0,0,0,0,0,2
31347,498642160540200960,fm7id2qd2mu7dd5lu6h1ses4b2,x,498642160540200960,"RT @iMoviePhrases: Si eres bueno en algo, nunc...",1518218509,2,0,0,0,0,0,2
31348,498642160540200960,i2nhjkbhkbkir86llscpbg2no4,x,498642160540200960,"RT @iMoviePhrases: Si eres bueno en algo, nunc...",1518218509,2,0,0,0,0,0,2

In [35]:
df = merged_df[['tweet_id','text','session_id', 'vote']]

In [42]:
df

,tweet_id,text,session_id,vote
0,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,04hfu1edim4o69ihnmeas70jj3,n
1,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,0re71cb38k4vbm0ab8ptfch9e1,3
2,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,1edr5icem4mtn3dgfqv1o99he2,1
3,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,eoqefm1vce3tecodb9i9g2avp7,4
4,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,fic8u9o83q8vq2jt2t4ed9vra4,1
...,...,...,...,...
31344,498640875581632512,RT @MichelPesquera: Las palabras que usamos pa...,0re71cb38k4vbm0ab8ptfch9e1,x
31345,498640875581632512,RT @MichelPesquera: Las palabras que usamos pa...,ftu0ov2469ncl5th6iqritm6o0,n
31346,498640875581632512,RT @MichelPesquera: Las palabras que usamos pa...,h1f2gvtplolcmuoi9didbl7285,x
31347,498642160540200960,"RT @iMoviePhrases: Si eres bueno en algo, nunc...",fm7id2qd2mu7dd5lu6h1ses4b2,x
31348,498642160540200960,"RT @iMoviePhrases: Si eres bueno en algo, nunc...",i2nhjkbhkbkir86llscpbg2no4,x

In [45]:
top_annotators = df['session_id'].value_counts()

In [56]:
top_annotators = top_annotators[:100]

In [63]:
type(top_annotators)

pandas.core.series.Series

In [66]:
top_annotators

session_id
fic8u9o83q8vq2jt2t4ed9vra4    2464
t2g54r2ehuch33kvl32ajjdd80    1341
qpp5nstf40o231sn2anvgj9842     621
i121cplbg3h5ck99jumnppeql1     566
c4pfqcj0qmo4f9kq64jito5bd4     554
                              ...
17464arrr3vutv3outklraeli0      60
dgnhovafp9scl1cltcb8i27do0      59
lclhi1ehob7d95i40204tkk4b5      59
3ea5iveejsp347oe5o9jvs52v3      57
2a0rau9l1klkiu9uqufdhph5n6      56
Name: count, Length: 100, dtype: int64

In [64]:
top_annotators_df = top_annotators.reset_index()
top_annotators_df.columns = ['session_id', 'count']

In [67]:
top_annotators_df['count'].sum()

17445

In [65]:
top_annotators_df

                    session_id  count
0   fic8u9o83q8vq2jt2t4ed9vra4   2464
1   t2g54r2ehuch33kvl32ajjdd80   1341
2   qpp5nstf40o231sn2anvgj9842    621
3   i121cplbg3h5ck99jumnppeql1    566
4   c4pfqcj0qmo4f9kq64jito5bd4    554
..                         ...    ...
95  17464arrr3vutv3outklraeli0     60
96  dgnhovafp9scl1cltcb8i27do0     59
97  lclhi1ehob7d95i40204tkk4b5     59
98  3ea5iveejsp347oe5o9jvs52v3     57
99  2a0rau9l1klkiu9uqufdhph5n6     56

[100 rows x 2 columns]

In [41]:
df['session_id'].nunique()

4582

In [68]:
tmp_df = pd.merge(df, top_annotators_df, on='session_id', how='inner')

In [70]:
tmp_df = tmp_df.drop(columns=['count'])

In [71]:
tmp_df

,tweet_id,text,session_id,vote
0,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,0re71cb38k4vbm0ab8ptfch9e1,3
1,21687932514,¿Qué es una elección? Lo que le pasa a un chin...,0re71cb38k4vbm0ab8ptfch9e1,4
2,27561052090,"Si tu apellido fuera Melculo, ¿cómo te gustarí...",0re71cb38k4vbm0ab8ptfch9e1,4
3,2057672085995520,Las piernas son las mejores amigas de una chic...,0re71cb38k4vbm0ab8ptfch9e1,1
4,2780034909601792,"-Señor, vengo a pedir las nalgas de su hija -L...",0re71cb38k4vbm0ab8ptfch9e1,2
...,...,...,...,...
17440,495711848688529408,Nunca uses a una persona para olvidar a otra. ...,fm7id2qd2mu7dd5lu6h1ses4b2,3
17441,497471855549493248,RT @DeboRecordarQue: Muchas veces la gente no ...,fm7id2qd2mu7dd5lu6h1ses4b2,x
17442,497472516089475074,RT @iDescubrelo: De las 6.900 lenguas que se h...,fm7id2qd2mu7dd5lu6h1ses4b2,x
17443,497525673796575234,Nunca me sale eso de dormirme temprano,fm7id2qd2mu7dd5lu6h1ses4b2,x
17444,498642160540200960,"RT @iMoviePhrases: Si eres bueno en algo, nunc...",fm7id2qd2mu7dd5lu6h1ses4b2,x

In [75]:
# Przekształcenie DataFrame'a
pivot_df = tmp_df.pivot_table(index=['tweet_id', 'text'], columns='session_id', values='vote', aggfunc='sum', fill_value=0)

# Zresetowanie indeksu
pivot_df = pivot_df.reset_index()

# Wyświetlenie DataFrame'a po przekształceniu
pivot_df[:5]

session_id,tweet_id,text,0c3jbu49tho46b5udmr99m8mp3,0lg96esg0sei07fo35n9o1dfv0,0mh1d1e0j45qt98gj2emndr9u3,0re71cb38k4vbm0ab8ptfch9e1,15luksqg9o7phlgfv5qgv3ctt6,171f256lbtk96v7dibnt656bg5,17464arrr3vutv3outklraeli0,1edr5icem4mtn3dgfqv1o99he2,...,t6oktkgtfbe5alq8rjmgbvrcv5,tesnno6fucv1um89opb8qb3kf3,thv26ne43fbb9hsrqsg75ntdg4,tkfro34k6nq49of2fl4d95vj83,tva30pd6v3857u3v0v2utqacj6,u9f4be86fglsekbqn92947ti56,uffpnou6daove1gvj2retde885,ugu5ran4euorifd91uqms7uuq7,ulcoup263danq62e213es97at3,vf7art6j8ir0kljq98sk6j9kb7
0,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,0,0,0,3,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,21687932514,¿Qué es una elección? Lo que le pasa a un chin...,0,0,0,4,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
2,27561052090,"Si tu apellido fuera Melculo, ¿cómo te gustarí...",0,0,0,4,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
3,2057672085995520,Las piernas son las mejores amigas de una chic...,0,0,0,1,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
4,2100110548795392,¿Cuál es la diferencia entre un burro y una TV...,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [81]:
pivot_df

session_id,tweet_id,text,0c3jbu49tho46b5udmr99m8mp3,0lg96esg0sei07fo35n9o1dfv0,0mh1d1e0j45qt98gj2emndr9u3,0re71cb38k4vbm0ab8ptfch9e1,15luksqg9o7phlgfv5qgv3ctt6,171f256lbtk96v7dibnt656bg5,17464arrr3vutv3outklraeli0,1edr5icem4mtn3dgfqv1o99he2,...,t6oktkgtfbe5alq8rjmgbvrcv5,tesnno6fucv1um89opb8qb3kf3,thv26ne43fbb9hsrqsg75ntdg4,tkfro34k6nq49of2fl4d95vj83,tva30pd6v3857u3v0v2utqacj6,u9f4be86fglsekbqn92947ti56,uffpnou6daove1gvj2retde885,ugu5ran4euorifd91uqms7uuq7,ulcoup263danq62e213es97at3,vf7art6j8ir0kljq98sk6j9kb7
0,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,0,0,0,3,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,21687932514,¿Qué es una elección? Lo que le pasa a un chin...,0,0,0,4,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
2,27561052090,"Si tu apellido fuera Melculo, ¿cómo te gustarí...",0,0,0,4,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
3,2057672085995520,Las piernas son las mejores amigas de una chic...,0,0,0,1,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
4,2100110548795392,¿Cuál es la diferencia entre un burro y una TV...,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7616,497831598663143425,RT @DebeSaberQue: El peor error que puedes com...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7617,497832362542383105,RT @AmorAmbiental: Reciclar los periódicos (el...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7618,497832646668742657,RT @MichelPesquera: Si el salario mínimo alcan...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7619,498640875581632512,RT @MichelPesquera: Las palabras que usamos pa...,0,0,0,x,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7620,498642160540200960,"RT @iMoviePhrases: Si eres bueno en algo, nunc...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
pivot_df = pivot_df.drop(columns=['session_id'])

KeyError: "['session_id'] not found in axis"

In [77]:
tmp_df[tmp_df['session_id']=='0re71cb38k4vbm0ab8ptfch9e1']

,tweet_id,text,session_id,vote
0,21687865379,¿Cómo se llama la maestra de los pollitos? ¡Mi...,0re71cb38k4vbm0ab8ptfch9e1,3
1,21687932514,¿Qué es una elección? Lo que le pasa a un chin...,0re71cb38k4vbm0ab8ptfch9e1,4
2,27561052090,"Si tu apellido fuera Melculo, ¿cómo te gustarí...",0re71cb38k4vbm0ab8ptfch9e1,4
3,2057672085995520,Las piernas son las mejores amigas de una chic...,0re71cb38k4vbm0ab8ptfch9e1,1
4,2780034909601792,"-Señor, vengo a pedir las nalgas de su hija -L...",0re71cb38k4vbm0ab8ptfch9e1,2
...,...,...,...,...
281,497411009574092800,"""Hola mijo, ¿como estas?, salúdame a tu Mamá""....",0re71cb38k4vbm0ab8ptfch9e1,x
282,497442141816123392,"—Bueno, abra las piernas.\r\n—Me da vergüenza....",0re71cb38k4vbm0ab8ptfch9e1,4
283,497466533510393856,VEAN ESTE VIDEO ES MUY GRACIOSO https://t.co/Y...,0re71cb38k4vbm0ab8ptfch9e1,x
284,497470567189323777,RT @MichelPesquera: Hay que aprender a darle a...,0re71cb38k4vbm0ab8ptfch9e1,x
285,498640875581632512,RT @MichelPesquera: Las palabras que usamos pa...,0re71cb38k4vbm0ab8ptfch9e1,x

In [83]:
pivot_df.to_csv('PreprocessedData/HUMOR/humor_100.csv', index=False)